FROM rayproject/ray:2.48.0-py39

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir \
    --index-url https://download.pytorch.org/whl/cu124 \
    --extra-index-url https://pypi.org/simple \
    -r requirements.txt

# RUN pip install --no-cache-dir \
#     numpy==1.24.3 \
#     pandas==2.0.3 \
#     scikit-learn==1.3.0

COPY train.py .

CMD ["python", "train.py"]