apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector
  labels:
    app: vector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vector
  template:
    metadata:
      labels:
        app: vector
    spec:
      containers:
        - name: vector
          image: docker.dev/timberio/vector:latest-debian
          volumeMounts:
            - name: config-volume
              mountPath: /etc/vector
          command: ["vector", "--config", "/etc/vector/vector.yaml"]
          env:
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vector-secrets
                  key: kafka-password
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vector-secrets
                  key: clickhouse-password
      volumes:
        - name: config-volume
          configMap:
            name: vector-config

